apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-9
  template:
    metadata:
      labels:
        app: project-9
    spec:
      containers:
      - name: project-9
        image: mukeshr29/project-9:v1.46
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9099
