apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels: 
    app: project-9
spec:
  selector:
    app: project-9
  type: LoadBalancer
  ports:
  - nodePort: 30036
    port: 80
    targetPort: 9099
